services:
  jenkins:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Esto podría ser útil si Docker está disponible en el contenedor
    networks:
      - my-network
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      DOCKER_HOST: "tcp://host.docker.internal:2375"  # Dirección de Docker en Windows usando WSL2

  maven-java:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: maven-java
    environment:
      - MAVEN_OPTS=-Xmx2g
    volumes:
      - ./app:/app
    working_dir: /app
    command: mvn clean install
    depends_on:
      - jenkins
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  jenkins_home: